#!/usr/bin/env python3
"""Build portable Musubi metadata and per-split cache TOML files from project manifests."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any


def _quote_toml(value: str) -> str:
    # JSON string encoding is valid TOML basic-string encoding for these paths.
    return json.dumps(value, ensure_ascii=False)


def _safe_dataset_path(dataset_root: Path, value: str) -> Path:
    candidate = Path(value)
    if candidate.is_absolute() or ".." in candidate.parts:
        raise ValueError(f"Expected project-relative dataset path, got {value!r}")
    resolved = (dataset_root / candidate).resolve()
    if dataset_root not in (resolved, *resolved.parents):
        raise ValueError(f"Path escapes dataset directory: {value!r}")
    return resolved


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _write_toml(
    path: Path,
    metadata_path: Path,
    cache_path: Path,
    resolution: int,
    control_resolution: int,
) -> None:
    content = "\n".join(
        [
            "# Generated by scripts/prepare_musubi_metadata.py; regenerate after moving the project.",
            "[general]",
            f"resolution = [{resolution}, {resolution}]",
            "batch_size = 1",
            "enable_bucket = true",
            "bucket_no_upscale = true",
            "",
            "[[datasets]]",
            f"image_jsonl_file = {_quote_toml(str(metadata_path.resolve()))}",
            f"cache_directory = {_quote_toml(str(cache_path.resolve()))}",
            "num_repeats = 1",
            # Musubi's Qwen-Image-Edit schema deliberately uses its
            # architecture-specific key; a generic `control_resolution` is
            # rejected by the validator.
            f"qwen_image_edit_control_resolution = [{control_resolution}, {control_resolution}]",
            "",
        ]
    )
    path.write_text(content, encoding="utf-8")


def prepare(root: Path, splits: list[str], resolution: int, control_resolution: int) -> dict[str, Any]:
    sys.path.insert(0, str(root))
    from qwen_enhance.constants import FIXED_ENHANCEMENT_PROMPT

    if resolution < 256 or resolution % 16:
        raise ValueError("resolution must be at least 256 and divisible by 16")
    if control_resolution < 256 or control_resolution % 16:
        raise ValueError("control-resolution must be at least 256 and divisible by 16")

    dataset_root = root / "dataset"
    manifests_root = dataset_root / "manifests"
    output_root = root / "artifacts" / "dataset"
    cache_root = root / "artifacts" / "cache"
    output_root.mkdir(parents=True, exist_ok=True)
    cache_root.mkdir(parents=True, exist_ok=True)
    report: dict[str, Any] = {
        "project_root": str(root),
        "resolution": resolution,
        "control_resolution": control_resolution,
        "splits": {},
    }

    for split in splits:
        source = manifests_root / f"{split}.jsonl"
        if not source.is_file():
            raise FileNotFoundError(f"Missing source manifest: {source}")
        output_metadata = output_root / f"{split}.jsonl"
        output_toml = output_root / f"{split}.toml"
        cache_path = cache_root / f"{split}_{resolution}x{resolution}_ctrl{control_resolution}"
        cache_path.mkdir(parents=True, exist_ok=True)

        generated: list[dict[str, str]] = []
        task_counts: Counter[str] = Counter()
        for line_no, record in enumerate(_load_jsonl(source), start=1):
            for field in ("id", "task", "input", "target"):
                if field not in record:
                    raise ValueError(f"{source}:{line_no} missing {field}")
            input_path = _safe_dataset_path(dataset_root, str(record["input"]))
            target_path = _safe_dataset_path(dataset_root, str(record["target"]))
            if not input_path.is_file() or not target_path.is_file():
                raise FileNotFoundError(f"Missing pair for {record['id']}: {input_path}, {target_path}")
            generated.append(
                {
                    "image_path": str(target_path),
                    "control_path": str(input_path),
                    "caption": FIXED_ENHANCEMENT_PROMPT,
                }
            )
            task_counts[str(record["task"])] += 1

        with output_metadata.open("w", encoding="utf-8", newline="\n") as handle:
            for item in generated:
                handle.write(json.dumps(item, ensure_ascii=False) + "\n")
        _write_toml(output_toml, output_metadata, cache_path, resolution, control_resolution)
        digest = hashlib.sha256(output_metadata.read_bytes()).hexdigest()
        report["splits"][split] = {
            "count": len(generated),
            "task_counts": dict(sorted(task_counts.items())),
            "metadata": str(output_metadata),
            "toml": str(output_toml),
            "cache_directory": str(cache_path),
            "sha256": digest,
        }

    report_path = output_root / "preparation_report.json"
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", default=Path(__file__).resolve().parents[1])
    parser.add_argument("--splits", nargs="+", default=["train", "val", "test"])
    parser.add_argument("--resolution", type=int, default=512)
    parser.add_argument("--control-resolution", type=int, default=512)
    args = parser.parse_args()
    report = prepare(
        Path(args.project_root).expanduser().resolve(),
        args.splits,
        args.resolution,
        args.control_resolution,
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
